services:
  server:
    container_name: credit-php
    image: yiisoftware/yii2-php:8.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - postgres

  db:
    image: postgres
    container_name: credit-postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=car-credit
      - POSTGRES_USER=credit-app
      - POSTGRES_PASSWORD=wow-much-secure-very-strong-so-unbreakable
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - postgres
volumes:
  db-data:

networks:
  postgres:
    driver: bridge